#!/bin/bash

# Global defaults
CLOSURE_COMPILER="/opt/local/lib/closure/compiler.jar"
FREQUENCY=5

# System override the defaults
if [ -f /etc/default/closure ]; then
        . /etc/default/closure
fi

if ! [ -r "$CLOSURE_COMPILER" ]; then
	echo "Error: cannot find the closer compiler $CLOSURE_COMPILER" >&2
	exit 1
fi

COMPILE="java -jar $CLOSURE_COMPILER"

# First argument can be the directory
if [ -n "$1" ]; then
        cd "$1" || exit 1
fi

### THE MEAT ###
################

# Cross-platform growl notification #
notify() {
        TEXT="$@"
        if which growlnotify >/dev/null 2>&1; then
                growlnotify -n "Closure Compiler" -w << _EOM_
$TEXT
_EOM_
        elif which notify-send >/dev/null 2>&1; then
                notify-send -t 3000 "Closure Compiler" "$TEXT" 2>/dev/null || echo "$TEXT"
	else
		echo "$TEXT"
        fi
}

# Cross-platform stat command #
if stat -c %Y . >/dev/null 2>&1 ; then
	STAT="stat -c %Y"
elif stat -f %c . >/dev/null 2>&1 ; then
	STAT="stat -f %c"
else
	echo "Error: Invalid stat version: " >&2
	stat --version >&2
	exit 1
fi


DIRECTORY=$(pwd)

echo "Scanning directory: $DIRECTORY ..."

while true; do
        find . -maxdepth 1 -name '*.js' | while read JSFILE; do
                # IGNORE already minified files
                [ $(basename $JSFILE .min.js) != $(basename $JSFILE) ] && continue
                JSMINFILE="$(basename $JSFILE .js).min.js"
                if [ -f $JSMINFILE ]; then
                        # checking if min file is older
                        if [ $($STAT $JSMINFILE) -lt $($STAT $JSFILE) ]; then
                                echo "  minifying: $JSFILE => $JSMINFILE"
                                MESSAGE=$($COMPILE --js $JSFILE --js_output_file $JSMINFILE 2>&1)
                                if [ $? -eq 0 ]; then
                                	notify ${MESSAGE:-$DIRECTORY/$(basename $JSFILE) => $JSMINFILE}
                                else
                                        notify "Error minifying $JSFILE, see the log for more details"
					echo "$MESSAGE" >&2
                                fi
                        fi
                else
                        echo "  minifying: $JSFILE => $JSMINFILE"
                        MESSAGE=$($COMPILE --js $JSFILE --js_output_file $JSMINFILE 2>&1)
                        if [ $? -eq 0 ]; then
                                notify ${MESSAGE:-$DIRECTORY/$(basename $JSFILE) => $JSMINFILE}
                        else
                                notify "Error minifying $JSFILE, see the log for more details"
				echo "$MESSAGE" >&2
                        fi
                fi
        done
        sleep $FREQUENCY
done
